### PR TITLE
Updating Scarb references to latest v2.8.1

### PR DESCRIPTION
**Pull request by stranger80**
This is a naive attempt to fix https://github.com/shramee/starklings-cairo1/issues/216 - as without these Starklings refuse to compile.

### CODE REVIEW

**Comment by enitrat** [comment]
@stranger80 thank you for updating starklings 🙏 can you update rust in CI to 1.80.0 ?

**Comment by stranger80** [comment]
Rust updated to 1.80.0 in workflow definition.

**Comment by shramee** [comment]
Build seems to be failing does it work when building/running locally?

**Comment by enitrat** [comment]
hm apparently 1.80.0 fials as well
i tried with 1.82.0-nightly and it works

**Comment by stranger80** [comment]
It works for me with 1.80.1 - shall we use that?

**Comment by enitrat** [comment]
yes we can

**Comment by shramee** [comment]
I'll leave this to you @enitrat

**Comment by stranger80** [comment]
OK, one more step was missing- force upadte the dependencies (`cargo update`) - this is required to get to the latest crate versions.

**Review by enitrat — APPROVED** [review]

**Comment by shramee** [comment]
@enitrat This seems to have commented out the build step in ci...
image

**Comment by enitrat** [comment]
Ah oops I didn't see the last commit 🤦

**Comment by shramee** [comment]
Aah actually, looks like CI is broken...

**Comment by shramee** [comment]
Addressed in #220

**Comment by shramee** [comment]
@enitrat We might have to undo this one, because we need Cairo v2.8 compatibility... Even after updating versions on runner crates... I'm getting this error...

image

**Comment by enitrat** [comment]
ah ok yes sorry 🙏 did this on mobile, let's revert

**Comment by shramee** [comment]
No worries, because of the broken CI file, the tests weren't run... So there weren't any errors on the PR.

**Comment by enitrat** [comment]
We can just add cfg(test) attribute on test modules I think

**Comment by shramee** [comment]
Didn't quite work...

It does work via scarb in the runner crate though... But not via Starklings.

**Comment by shramee** [comment]
Fixed serde...
https://github.com/shramee/starklings-cairo1/pull/221#discussion_r1746040133

**Pull request merged**
