### PR TITLE
Updated README.md for Options

### PR DESCRIPTION
**Pull request by fishonamos**
Improved grammar and readability in documentation for `Option` type usage and applications"

### CODE REVIEW

**Review by shramee — CHANGES_REQUESTED** [review]
Hi, some markup to highlight language keywords without changing the sentences themselves could be helpful here.

**Comment by fishonamos** [comment]
Noted. I will do that now.

**Comment by fishonamos** [comment]
Hi @shramee . I have removed the sentences changes. Only the markup highlight for the language keywords are left.

**Review by shramee — APPROVED** [review]

**Comment by shramee** [comment]
Thanks @fishonamos This makes it much easier to read!
We are not yet sure if we want to keep these readmes but I'll merge it for now.

**Pull request merged**
