### PR TITLE
fix: speed up cairo-runner and cairo-tester in starklings

### LINKED ISSUE #25: Speed up starklings run
The running/verification step of a cairo program takes too much time when called by `starklings run program.cairo` compared to natively call `cairo-tester run program.cairo`. We need to find a way to make it faster

### PR DESCRIPTION
**Pull request by msaug**
Fixes #25 
The user will need to build the binaries before using starklings with `cargo build --all`.
We invoke directly the executables in starklings instead of using cargo, which speeds things up _at least_ 10x.

Time spent: 3 hours

### CODE REVIEW

**Comment by msaug** [comment]
will look into the CI problem later

**Comment by shramee** [comment]
Hi @msaug,

It's nice to have this to be able to run things faster, but we want to be able to run it with `cargo run` too to avoid having to build and going to a specific dir.

People shouldn't have to be well versed in terminal to use Starklings and instructions to get start should be minimal.

**Comment by msaug** [comment]
> People shouldn't have to be well versed in terminal to use Starklings and instructions to start should be minimal.

While I agree about this, it takes up to 30 seconds to verify each exercise when invoking the runners with the cargo command because it verifies the version and state of all the dependencies on each start.

Imagine if you have done every exercise and are now working on structs, it means that you have to wait nearly 5 minutes for every exercise prior to structs to be verified which is frankly unusable


Perhaps we could use a Makefile to make it easier for the user?


The easiest solution would be to install everything with `cargo install .` to make the executables available from the terminal. The only problem with this approach is that the core library is not installed with that binaries and the program cannot run.

While I agree with your comment, something must be done to speed things up.

**Comment by shramee** [comment]
I see what you mean...
I think a nice way around that would be to perhaps make `Exercise::run_cairo()` use a rust function itself instead of running another command?
https://github.com/shramee/starklings-cairo1/blob/main/src/exercise.rs#L93

You can look at my old code at [shramee/creative-cairo](https://github.com/shramee/creative-cairo/blob/main/src/run_cairo.rs) for reference if you like.

**Comment by msaug** [comment]
I agree with this as a temporary solution. When Cairo 1 is properly released we will get rid of `cairo-runner` and `cairo-tester` and run `cairo-run` and `cairo-test` from the Cairo binaries directly, but we have time for that :)

**Comment by msaug** [comment]
It is now **_BLAZINGLY FAST_** especially when running in release mode ;)

**Comment by shramee** [comment]
### 🥳 🚀

**Pull request merged**
