### PR TITLE
bug: sytnatical errors was raised in options3 fixed

### PR DESCRIPTION
**Pull request by karasakalmt**

### CODE REVIEW

**Comment by karasakalmt** [comment]
Related error
```
[Error - 5:10:38 PM] Request textDocument/semanticTokens/full failed.
  Message: Internal error
  Code: -32603 
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `TerminalLBrack`,
 right: `TerminalLParen`', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cairo-lang-parser-2.0.2/src/parser.rs:1946:9
Caught panic in LSP worker thread.
```

**Comment by shramee** [comment]
@karasakalmt Not sure I see the issue...

**Comment by karasakalmt** [comment]
@shramee can you please open it in VSCode I got the error above from the Cairo1.0 plugin

**Comment by shramee** [comment]
Aah, Starklings uses Cairo 2.

**Comment by shramee** [comment]
We should rename to Starklings Cairo 2 now 😂

**Pull request closed without merging**
